# Generated by Django 5.2.7 on 2025-11-27 05:05

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=api.models.avatar_upload_to)),
                ('language', models.CharField(default='en', max_length=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('dark_mode', models.BooleanField(default=False)),
                ('accent_color', models.CharField(default='#6366f1', max_length=9)),
                ('sound', models.BooleanField(default=True)),
                ('haptics', models.BooleanField(default=True)),
                ('app_lock_enabled', models.BooleanField(default=False)),
                ('app_lock_pin_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('notifications_daily_summary', models.BooleanField(default=False)),
                ('auto_backup_enabled', models.BooleanField(default=False)),
                ('auto_backup_schedule', models.CharField(default='daily', max_length=20)),
                ('storage_provider', models.CharField(choices=[('local', 'LocalStorage'), ('pinia', 'Pinia'), ('supabase', 'Supabase'), ('firebase', 'Firebase'), ('vuex', 'Vuex')], default='local', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
